### PR TITLE
Feature/gradle build plus readme

### PR DESCRIPTION
**Pull request by kungfoo**
I took the liberty of adding a gradle build (I'm more that kinda guy, plus it's faster and self-priming (apart from the JDK)) and a README.
See you in the evening.

### CODE REVIEW

**Comment by jwloka** [comment]
@kungfoo Looks good. Thanks!

**Comment by kungfoo** [comment]
Just forget that. Looked at the wrong code. :)

**Comment by jwloka** [comment]
No worries. In about an hour or so : )

**Comment by jwloka** [comment]
@kungfoo Merged and pushed. Thx!

**Pull request merged**
